from __future__ import annotations

import uuid
from typing import Protocol

from app.modules.grades.domain.grade import Grade


class GradeRepository(Protocol):
    async def get(self, grade_id: uuid.UUID) -> Grade | None: ...
    async def get_for_student_course(
        self, student_id: uuid.UUID, course_id: uuid.UUID
    ) -> Grade | None: ...
    async def list_for_student(self, student_id: uuid.UUID) -> list[Grade]: ...
    async def list_for_course(self, course_id: uuid.UUID) -> list[Grade]: ...
    async def add(self, grade: Grade) -> None: ...
    async def update(self, grade: Grade) -> None: ...
