from __future__ import annotations

import uuid
from typing import Protocol

from app.modules.teachers.domain.teacher import Teacher


class TeacherRepository(Protocol):
    async def add(self, teacher: Teacher) -> None: ...

    async def get(self, teacher_id: uuid.UUID) -> Teacher | None: ...

    async def get_by_email(self, email: str) -> Teacher | None: ...

    async def list(self, *, offset: int, limit: int, search: str | None) -> list[Teacher]: ...

    async def count(self, *, search: str | None) -> int: ...

    async def update(self, teacher: Teacher) -> None: ...

    async def delete(self, teacher_id: uuid.UUID) -> None: ...
